import type { RobotSpec } from '../robot/spec';
import type { Device } from '../robot/ports';
import { externalRatio, wheelTravelMm } from '../robot/metrics';

const RATIO = { red: 'ratio36_1', green: 'ratio18_1', blue: 'ratio6_1' } as const;

export interface CodeFileGen { path: string; content: string; generated: boolean }

function header(spec: RobotSpec, version: number) {
  return `// AUTO-GENERATED by FDRHS Robotics Hub from "${spec.meta.name}" v${version} — change the build, not this file.`;
}

function motorLine(d: Device) {
  const ratio = d.motorType === '5.5W' ? 'ratio18_1' : RATIO[d.cartridge ?? 'green'];
  const note = d.motorType === '5.5W' ? ' // 5.5 W motor: fixed 200 rpm output (verify gear setting in VEXcode)' : '';
  return `motor ${d.name} = motor(PORT${d.port}, ${ratio}, ${d.reversed ? 'true' : 'false'});${note}`;
}

export function generateRobotConfig(spec: RobotSpec, devices: Device[], version: number): { cpp: string; h: string } {
  const dt = spec.drivetrain;
  const motors = devices.filter((d) => d.type === 'motor');
  const groups = new Map<string, Device[]>();
  for (const m of motors) if (m.group) groups.set(m.group, [...(groups.get(m.group) ?? []), m]);
  const imu = devices.find((d) => d.type === 'inertial');
  const D = dt.wheel.diameterIn;
  const ratio = externalRatio(dt.gearing);
  const travel = wheelTravelMm(D) * ratio;
  const lines: string[] = [];
  const decl: string[] = [];
  lines.push(header(spec, version), '#include "vex.h"', '', 'using namespace vex;', '', '// A global instance of brain used for printing to the V5 Brain screen', 'brain Brain;', 'controller Controller1 = controller(primary);', '');
  decl.push(header(spec, version), '#pragma once', '', 'using namespace vex;', '', 'extern brain Brain;', 'extern controller Controller1;');
  lines.push('// ---- motors ----');
  for (const m of motors) { lines.push(motorLine(m)); decl.push(`extern motor ${m.name};`); }
  if (groups.size) lines.push('', '// ---- motor groups ----');
  for (const [g, ms] of groups) { lines.push(`motor_group ${g} = motor_group(${ms.map((m) => m.name).join(', ')});`); decl.push(`extern motor_group ${g};`); }
  const sensors = devices.filter((d) => ['inertial', 'rotation', 'optical', 'distance', 'gps', 'ai-vision'].includes(d.type));
  if (sensors.length) lines.push('', '// ---- sensors ----');
  for (const s of sensors) {
    switch (s.type) {
      case 'inertial': lines.push(`inertial ${s.name} = inertial(PORT${s.port});`); decl.push(`extern inertial ${s.name};`); break;
      case 'rotation': lines.push(`rotation ${s.name} = rotation(PORT${s.port}, false);`); decl.push(`extern rotation ${s.name};`); break;
      case 'optical': lines.push(`optical ${s.name} = optical(PORT${s.port});`); decl.push(`extern optical ${s.name};`); break;
      case 'distance': lines.push(`distance ${s.name} = distance(PORT${s.port});`); decl.push(`extern distance ${s.name};`); break;
      case 'gps': lines.push(`gps ${s.name} = gps(PORT${s.port}, 0.0, 0.0, mm, 180);`); decl.push(`extern gps ${s.name};`); break;
      case 'ai-vision': lines.push(`// AI Vision on PORT${s.port}: configure it in VEXcode's device menu`); break;
    }
  }
  const tw = devices.filter((d) => d.type === 'piston' || d.type === 'bumper' || d.type === 'limit');
  if (tw.length) lines.push('', '// ---- three-wire ----');
  for (const d of tw) {
    const cls = d.type === 'piston' ? 'digital_out' : d.type;
    lines.push(`${cls} ${d.name} = ${cls}(Brain.ThreeWirePort.${d.port});`);
    decl.push(`extern ${cls} ${d.name};`);
  }
  lines.push('', '// ---- drivetrain ----');
  lines.push(`// WHEEL_TRAVEL_MM is the travel per MOTOR revolution: π × ${D}″ × 25.4 × (${dt.gearing ? `${dt.gearing.driving}/${dt.gearing.driven}` : '1'}) = ${travel.toFixed(2)} mm.`);
  lines.push('// Passing it with externalGearRatio = 1.0 avoids gear-ratio ambiguity.');
  lines.push(`const double WHEEL_TRAVEL_MM = ${travel.toFixed(2)};`);
  lines.push(`const double TRACK_WIDTH_MM = ${(dt.trackWidthIn * 25.4).toFixed(2)};`);
  lines.push(`const double WHEEL_BASE_MM = ${(dt.wheelBaseIn * 25.4).toFixed(2)};`);
  const left = groups.has('leftDrive') ? 'leftDrive' : motors[0]?.name;
  const right = groups.has('rightDrive') ? 'rightDrive' : motors[1]?.name;
  if (imu) {
    lines.push(`smartdrive drive = smartdrive(${left}, ${right}, ${imu.name}, WHEEL_TRAVEL_MM, TRACK_WIDTH_MM, WHEEL_BASE_MM, mm, 1.0);`);
    decl.push('extern smartdrive drive;');
  } else {
    lines.push(`drivetrain drive = drivetrain(${left}, ${right}, WHEEL_TRAVEL_MM, TRACK_WIDTH_MM, WHEEL_BASE_MM, mm, 1.0);`);
    decl.push('extern drivetrain drive;');
  }
  lines.push('', 'void vexcodeInit(void) {');
  if (imu) lines.push(`  Brain.Screen.print("Calibrating inertial...");`, `  ${imu.name}.calibrate();`, `  while (${imu.name}.isCalibrating()) {`, '    wait(50, msec);', '  }', '  Brain.Screen.clearScreen();', '  Brain.Screen.setCursor(1, 1);');
  lines.push(`  Brain.Screen.print("FDRHS ${spec.meta.name.replace(/"/g, '')} ready");`, '}', '');
  decl.push('', 'void vexcodeInit(void);', '');
  return { cpp: lines.join('\n'), h: decl.join('\n') };
}

export const VEX_H = `/*----------------------------------------------------------------------------*/
/*    Module:       vex.h                                                     */
/*    Description:  Default header for V5 projects                            */
/*----------------------------------------------------------------------------*/
#pragma once

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "v5.h"
#include "v5_vcs.h"

#define waitUntil(condition)                                                   \\
  do {                                                                         \\
    wait(5, msec);                                                             \\
  } while (!(condition))

#define repeat(iterations)                                                     \\
  for (int iterator = 0; iterator < iterations; iterator++)

#include "robot-config.h"
`;

export function driveControl(spec: RobotSpec, devices: Device[]): string {
  const dt = spec.drivetrain;
  const m = (n: string) => devices.find((d) => d.name === n)?.name;
  if (dt.type === 'mecanum' || dt.type === 'xdrive') {
    const lf = m('leftFrontMotor') ?? 'leftFrontMotor', lb = m('leftBackMotor') ?? 'leftBackMotor';
    const rf = m('rightFrontMotor') ?? 'rightFrontMotor', rb = m('rightBackMotor') ?? 'rightBackMotor';
    return [
      '    int fwd = Controller1.Axis3.position();',
      '    int strafe = Controller1.Axis4.position();',
      '    int turn = Controller1.Axis1.position();',
      `    ${lf}.spin(forward, fwd + strafe + turn, percent);`,
      `    ${lb}.spin(forward, fwd - strafe + turn, percent);`,
      `    ${rf}.spin(forward, fwd - strafe - turn, percent);`,
      `    ${rb}.spin(forward, fwd + strafe - turn, percent);`,
    ].join('\n');
  }
  const out = [
    '    leftDrive.spin(forward, Controller1.Axis3.position(), percent);',
    '    rightDrive.spin(forward, Controller1.Axis2.position(), percent);',
  ];
  if (dt.type === 'hdrive') out.push('    strafeMotor.spin(forward, Controller1.Axis4.position(), percent);');
  return out.join('\n');
}

const BUTTONS: Record<string, [string, string] | string> = { intake: ['R1', 'R2'], lift: ['L1', 'L2'] };

export function mechanismControl(spec: RobotSpec, devices: Device[]): { code: string; controls: string[] } {
  const out: string[] = [];
  const controls: string[] = [];
  const target = (subId: string) => {
    const ms = devices.filter((d) => d.subsystemId === subId && d.type === 'motor');
    if (!ms.length) return null;
    return ms[0].group ?? ms[0].name;
  };
  const used = new Set<string>();
  for (const s of spec.subsystems) {
    const t = target(s.id);
    if ((s.type === 'intake' || s.type === 'lift') && t) {
      const [a, b] = BUTTONS[s.type] as [string, string];
      if (used.has(a)) continue;
      used.add(a);
      const stop = s.type === 'lift' ? 'hold' : 'brake';
      out.push(`    if (Controller1.Button${a}.pressing()) {`, `      ${t}.spin(forward, 100, percent);`, `    } else if (Controller1.Button${b}.pressing()) {`, `      ${t}.spin(reverse, 100, percent);`, '    } else {', `      ${t}.stop(${stop});`, '    }');
      controls.push(`| ${a} / ${b} | ${s.name} ${s.type === 'lift' ? 'up / down (hold when released)' : 'in / out (brake when released)'} |`);
    }
  }
  const piston = (type: string, btn: string, label: string) => {
    const p = devices.find((d) => d.type === 'piston' && spec.subsystems.find((s) => s.id === d.subsystemId)?.type === type);
    if (!p || used.has(btn)) return;
    used.add(btn);
    out.push(`    if (Controller1.Button${btn}.pressing()) {`, `      ${p.name}.set(!${p.name}.value());`, `      waitUntil(!Controller1.Button${btn}.pressing());`, '    }');
    controls.push(`| ${btn} | Toggle ${label} |`);
  };
  piston('clamp', 'A', 'the clamp');
  piston('wing', 'B', 'wings');
  const launcher = spec.subsystems.find((s) => s.type === 'launcher');
  if (launcher && target(launcher.id)) {
    out.push('    if (Controller1.ButtonX.pressing()) {', `      ${target(launcher.id)}.spin(forward, 100, percent);`, '    } else {', `      ${target(launcher.id)}.stop(coast);`, '    }');
    controls.push('| X | Fire the launcher |');
  }
  const hang = spec.subsystems.find((s) => s.type === 'hang');
  if (hang) {
    const hp = devices.find((d) => d.subsystemId === hang.id && d.type === 'piston');
    if (hp) { out.push('    if (Controller1.ButtonY.pressing()) {', `      ${hp.name}.set(true);`, '    }'); controls.push('| Y | Hang |'); }
  }
  return { code: out.join('\n'), controls };
}

export function generateMainCpp(spec: RobotSpec, devices: Device[], extraIncludes: string[] = []): string {
  const mech = mechanismControl(spec, devices);
  return `#include "vex.h"
${extraIncludes.map((i) => `#include "${i}"`).join('\n')}${extraIncludes.length ? '\n' : ''}using namespace vex;

competition Competition;

void pre_auton(void) {
  vexcodeInit();
}

void autonomous(void) {
  drive.setDriveVelocity(60, percent);
  drive.setTurnVelocity(40, percent);
  drive.driveFor(forward, 24, inches);
  drive.turnFor(right, 90, degrees);
}

void usercontrol(void) {
  while (true) {
${driveControl(spec, devices)}
${mech.code}
    wait(20, msec);
  }
}

int main() {
  Competition.autonomous(autonomous);
  Competition.drivercontrol(usercontrol);
  pre_auton();
  while (true) {
    wait(100, msec);
  }
}
`;
}

export function controlsMd(spec: RobotSpec, devices: Device[]): string {
  const mech = mechanismControl(spec, devices);
  const drive = spec.drivetrain.type === 'mecanum' || spec.drivetrain.type === 'xdrive'
    ? '| Left stick | Drive + strafe |\n| Right stick (X) | Turn |'
    : '| Left stick (Axis 3) | Left side |\n| Right stick (Axis 2) | Right side |';
  const ports = devices.map((d) => `| ${d.name} | ${d.type}${d.motorType ? ` ${d.motorType}${d.cartridge ? ` ${d.cartridge}` : ''}` : ''} | ${typeof d.port === 'number' ? `PORT${d.port}` : d.port} |`).join('\n');
  return `# ${spec.meta.name} — controls and ports\n\n## Controller\n\n| Buttons | Action |\n|---|---|\n${drive}\n${mech.controls.join('\n')}\n\n## Port map\n\n| Device | Type | Port |\n|---|---|---|\n${ports}\n`;
}

export function projectReadme(spec: RobotSpec, version: number): string {
  return `# ${spec.meta.name} v${version} — VEXcode V5 project

Generated by FDRHS Robotics Hub.

## Open it
- **VEXcode V5**: File → Open → choose this folder (or import the files into a new C++ project).
- **VS Code + VEX extension**: open this folder, then use the VEX sidebar to build and download.

## Download to the Brain
Plug the Brain into USB, pick a program slot, and click Download. The web app checks your code
against the VEX V5 C++ API but cannot download to the Brain.

\`src/robot-config.cpp\` and \`include/robot-config.h\` are generated from the build — change the build, not those files.
`;
}

export const SEED_FILES = {
  'include/intake-control.h': `// FDRHS Robotics - Intake Control
void setup() {
  Brain.Screen.print("FDRHS");
  intakeMotor.setStopping(brakeType::brake);
}

void loop() {
  if (Controller1.ButtonR1.pressing()) {
    intakeMotor.spin(forward, 100, percent);
  }
}
`,
  'include/autonomous.h': `// FDRHS Robotics - Autonomous
void auton() {
  drive.driveFor(forward, 600, mm);
  wait(500, msec);
  intakeMotor.spin(forward);
}
`,
};
