import { execFileSync } from 'node:child_process';
import { describe, expect, it } from 'vitest';
import { derive } from '@/lib/robot/derive';
import { SEED_SPEC, TEMPLATES } from '@/lib/robot/defaults';
import { generateMainCpp, generateRobotConfig, VEX_H, SEED_FILES } from '@/lib/vexcode/generate';
import { compileProject } from '@/lib/vexcode/compile';

let hasGxx = true;
try { execFileSync(process.env.GXX_PATH || 'g++', ['--version'], { stdio: 'ignore' }); } catch { hasGxx = false; }

describe('robot-config generation', () => {
  it('competition base: WHEEL_TRAVEL_MM 194.50 (3.25″, 36:48)', () => {
    const d = derive(TEMPLATES['competition-base'].spec('Comp'));
    const rc = generateRobotConfig(d.spec, d.devices, 1);
    expect(rc.cpp).toMatch(/194\.50/);
    expect(rc.cpp).toMatch(/AUTO-GENERATED by FDRHS Robotics Hub/);
    expect(rc.h).toMatch(/void vexcodeInit\(void\);/);
  });
  it('maps cartridges to gear ratios', () => {
    const d = derive(TEMPLATES['competition-base'].spec('Comp'));
    expect(generateRobotConfig(d.spec, d.devices, 1).cpp).toMatch(/ratio6_1/);
  });
});

describe.skipIf(!hasGxx)('generated projects compile with g++ against the V5 stubs', () => {
  const specs = { seed: SEED_SPEC, ...Object.fromEntries(Object.entries(TEMPLATES).map(([k, t]) => [k, t.spec(k)])) };
  it.each(Object.entries(specs))('%s', async (_n, spec) => {
    const d = derive(spec);
    const rc = generateRobotConfig(d.spec, d.devices, 1);
    const files = [
      { path: 'include/vex.h', content: VEX_H }, { path: 'include/robot-config.h', content: rc.h }, { path: 'src/robot-config.cpp', content: rc.cpp },
      { path: 'src/main.cpp', content: generateMainCpp(d.spec, d.devices) },
    ];
    const r = await compileProject(files, d.devices.map((x) => x.name));
    expect(r.diagnostics.filter((x) => x.severity === 'error')).toEqual([]);
  }, 30_000);
  it('reports a typo as an error', async () => {
    const d = derive(SEED_SPEC);
    const rc = generateRobotConfig(d.spec, d.devices, 1);
    const main = generateMainCpp(d.spec, d.devices).replace('vexcodeInit();', 'vexcodeInt();');
    const r = await compileProject([{ path: 'include/vex.h', content: VEX_H }, { path: 'include/robot-config.h', content: rc.h }, { path: 'src/robot-config.cpp', content: rc.cpp }, { path: 'src/main.cpp', content: main }], []);
    expect(r.ok).toBe(false);
    expect(r.diagnostics[0].file).toBe('src/main.cpp');
  }, 30_000);
  it('seed student headers compile', () => {
    expect(Object.keys(SEED_FILES)).toContain('include/autonomous.h');
  });
});
